version: '3'
services:
  app:
    container_name: docker-node-mongodb
    restart: always
    build: .
    ports:
      - '8082:3000'
    links:
      - mongo
  mongo:
    container_name: mongodb
    image: mongo
    ports:
      - '27012:27017'
  mongo-express:
    image: "mongo-express:latest"
    ports:
      - "8081:8081"
  
